#include "ports.h"
#include "translation.h"
#include "positions.h"
#include "tasks.h"
#include "servos.h"
#include "threads.h"
#include <kipr/wombat.h>
#include <stdio.h>
#include <pthread.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>