name: CI

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: sillyfreak/wombat-cross
            options: --user root

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              env:
                  DEBIAN_FRONTEND: noninteractive
              run: |
                  apt-get update
                  apt-get install -y -q cmake build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

            - name: Configure project
              run: |
                  mkdir -p build
                  cd build
                  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc ..

            - name: Build
              run: |
                  cd build
                  cmake --build .
